---
scenario: 
  name: default

dependency:
  enabled: true
  name: galaxy
driver:
  name: docker

platforms:
  - name: docker-ubuntu
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    privileged: true
provisioner:
  name: ansible

verifier:
  name: ansible
