---
- name: ensure target directory exists
  file:
    path: "{{ cni_plugin_dir }}"
    state: directory

- name: download plugins and extract them
  unarchive:
    remote_src: true
    src: "{{ cni_plugin_release_url }}/{{ cni_plugin_release_version }}/cni-plugins-linux-amd64-{{ cni_plugin_release_version }}.tgz"
    dest: "{{ cni_plugin_dir }}"
    owner: root
    group: root
    mode: "0755"

- name: enable container routing through iptables
  ansible.posix.sysctl:
    name: "{{ item }}"
    state: present
    value: 1
    reload: true
    ignoreerrors: "{{ cni_plugin_sysctl_ignore_unknown_keys | bool }}"
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-ip6tables
  when: ansible_virtualization_type not in ['docker', 'lxc', 'openvz']
